name: Windows RustDesk Setup

on:
  workflow_dispatch:

jobs:
  rustdesk:
    runs-on: windows-latest
    steps:
    - name: Download RustDesk
      run: |
        # Download the RustDesk executable
        Invoke-WebRequest -Uri https://github.com/rustdesk/rustdesk/releases/download/1.2.7/rustdesk-1.2.7-x86_64.exe -OutFile rustdesk.exe

    - name: Start RustDesk and Capture ID/Password
      run: |
        # Start RustDesk and capture output
        Start-Process -FilePath ./rustdesk.exe -ArgumentList "-s" -RedirectStandardOutput "./rustdesk_log.txt" -NoNewWindow -Wait

        # Wait for RustDesk to start and generate ID/Password
        Start-Sleep -Seconds 10

        # Display the RustDesk log file with ID/Password
        Get-Content -Path "./rustdesk_log.txt"

    - name: Keep runner alive
      run: |
        Write-Host "RustDesk is running. Keeping the GitHub runner alive..."
        while ($true) {
          Start-Sleep -Seconds 60
        }
