name: Windows RustDesk Setup

on:
  workflow_dispatch:

jobs:
  rustdesk:
    runs-on: windows-latest
    steps:
    - name: Download RustDesk
      run: |
        Invoke-WebRequest -Uri https://github.com/rustdesk/rustdesk/releases/download/1.2.0/rustdesk-1.2.0-windows.zip -OutFile rustdesk.zip
        Expand-Archive -Path rustdesk.zip -DestinationPath .
        Move-Item -Path "./rustdesk-1.2.0-windows/*" -Destination . -Force

    - name: Start RustDesk and Capture ID/Password
      run: |
        # Start RustDesk in service mode and capture the output
        Start-Process -FilePath ./rustdesk.exe -ArgumentList "-s" -RedirectStandardOutput "./rustdesk_log.txt" -NoNewWindow -Wait

        # Wait for RustDesk to start up and generate the ID and password
        Start-Sleep -Seconds 10

        # Display the RustDesk log file which contains the ID and password
        Get-Content -Path "./rustdesk_log.txt"

    - name: Keep runner alive
      run: |
        Write-Host "RustDesk is running. Keeping the GitHub runner alive..."
        while ($true) {
          Start-Sleep -Seconds 60
        }
