name: Windows RDP Setup

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
    - name: Set up RDP environment
      run: |
        # Set RDP username and password
        $username = "rdpuser"
        $password = "P@ssw0rd123"
        
        # Create the user and set the password
        net user $username $password /add
        net localgroup administrators $username /add
        
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -name "fDenyTSConnections" -Value 0
        
        # Configure RDP settings
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fSingleSessionPerUser /t REG_DWORD /d 0 /f
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 1 /f
        
        # Enable the RDP firewall rule
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Allow ICMP for ping (optional, useful for troubleshooting connectivity)
        Enable-NetFirewallRule -Name FPS-ICMP4-ERQ-In
        
        # Show current RDP status
        quser
        
    - name: Get IP address
      run: |
        $ip = (Invoke-RestMethod -Uri "http://ifconfig.me/ip").Trim()
        Write-Host "Use this IP address to connect via RDP: $ip"
