name: Windows RDP Setup

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
    - name: Set up RDP environment
      run: |
        # Set RDP username and password
        $username = "rdpuser"
        $password = "P@ssw0rd123"
        
        # Create the user and set the password
        net user $username $password /add
        net localgroup administrators $username /add
        
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Install Chrome Remote Desktop or similar tools if needed
        # (Optional) Customize installation for any required RDP tools
        
        echo "RDP Setup Complete. You can connect to this runner using the username $username and the specified password."

    - name: Get IP address
      run: |
        $ip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content.Trim()
        echo "Use this IP address to connect via RDP: $ip"
